GET http://localhost:3000/count
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoiRGFuaWVsIiwiaWF0IjoxNzEzNTE4MzY2LCJleHAiOjE3MTM1MjE5NjZ9.laWAeHKLE0WlC_wnuTr98wSQkfEuJs3bvJkN-cSb9X8