GET http://localhost:3000/posts/get-comments/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6IlN0ZXBoIiwiaWF0IjoxNzE0Mzg1NDkzLCJleHAiOjE3MTQzODkwOTN9.6rhXYWZpSmer43taUihPPipj-t0afLKU1xFeWhqBxvM