GET http://localhost:3000/usergroups/userwithgroups?userId=10
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoiRGFuaWVsIiwiaWF0IjoxNzEzMzg1NzM1LCJleHAiOjE3MTMzODkzMzV9.tkZSPuFJDQdtND7ClUE4Germ1EAB0NAmENGSvyg3MDQ


