GET http://localhost:3000/usergroups/joinusergroups/2
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoiRGFuaWVsIiwiaWF0IjoxNzEzNjMxMjg2LCJleHAiOjE3MTM2MzQ4ODZ9.45y27c3lC6pPsYiF93nmJb5iloi987cFjo6F6aTBJlQ