GET http://localhost:3000/users/user-data/25
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6IlN0ZXBoIiwiaWF0IjoxNzEzOTA3ODk2LCJleHAiOjE3MTM5MTE0OTZ9.yg0oLj1XFfy_x3ZJXEeztPZBa266jaBrcmEqXt9VSEg
