GET http://localhost:3000/messages/10/31
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6IlN0ZXBoIiwiaWF0IjoxNzE1MDkxNjc0LCJleHAiOjE3MTUxMjc2NzR9.Uq9b8T96jQZMPt8FVgwM26kjiyQgpJcob9eQFAb5Qqc