POST http://localhost:3000/usergroups/
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoiRGFuaWVsIiwiaWF0IjoxNzEzMzY0MjE5LCJleHAiOjE3MTMzNjc4MTl9.ns2SJ0Sf74yKe69iRoX0du5g2oAw0fZNTbHfnk7-yeE

{
  "userId" : 3,
  "groupId" : 2
}